version: "3.8"
services:
        notes_db:
                image: postgres
                environment:
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                ports:
                        - '5432:5432'
                volumes:
                        - /var/notes_db:/var/lib/postgresql/data

